In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
import pickle

In [2]:
data=pd.read_csv("C:/Users/yagne/Desktop/anaconda/croppred/Crop_recommendation.csv")

In [3]:
data.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
l=list(data['label'].unique())
print(l)
print(type(l))

['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas', 'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate', 'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple', 'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee']
<class 'list'>


In [8]:
d=dict()
for i in range(len(l)):
    d[l[i]]=i
d

{'rice': 0,
 'maize': 1,
 'chickpea': 2,
 'kidneybeans': 3,
 'pigeonpeas': 4,
 'mothbeans': 5,
 'mungbean': 6,
 'blackgram': 7,
 'lentil': 8,
 'pomegranate': 9,
 'banana': 10,
 'mango': 11,
 'grapes': 12,
 'watermelon': 13,
 'muskmelon': 14,
 'apple': 15,
 'orange': 16,
 'papaya': 17,
 'coconut': 18,
 'cotton': 19,
 'jute': 20,
 'coffee': 21}

In [17]:
data1 = data.copy()

In [18]:
data1.replace(d, inplace=True)
data1

N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536      0
1      85  58  41    21.770462  80.319644  7.038096  226.655537      0
2      60  55  44    23.004459  82.320763  7.840207  263.964248      0
3      74  35  40    26.491096  80.158363  6.980401  242.864034      0
4      78  42  42    20.130175  81.604873  7.628473  262.717340      0
...   ...  ..  ..          ...        ...       ...         ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507     21
2196   99  15  27    27.417112  56.636362  6.086922  127.924610     21
2197  118  33  30    24.131797  67.225123  6.362608  173.322839     21
2198  117  32  34    26.272418  52.127394  6.758793  127.175293     21
2199  104  18  30    23.603016  60.396475  6.779833  140.937041     21

[2200 rows x 8 columns]

In [4]:
'''
fig, ax = plt.subplots(1, 1, figsize=(15, 9))
sns.countplot(data=data, x='label')
ax.set(xlabel='Crop')
ax.set(ylabel='Count')
plt.xticks(rotation=45)

plt.title('Count of crop', fontsize = 20, c='black')
plt.show()
'''

"\nfig, ax = plt.subplots(1, 1, figsize=(15, 9))\nsns.countplot(data=data, x='label')\nax.set(xlabel='Crop')\nax.set(ylabel='Count')\nplt.xticks(rotation=45)\n\nplt.title('Count of crop', fontsize = 20, c='black')\nplt.show()\n"

In [19]:
feat=data1[["temperature","humidity","ph","rainfall"]]

In [20]:
tar=data1[["label"]]

In [21]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(feat,tar,test_size = 0.2,random_state =2)

In [22]:
print(Xtrain.shape,Ytrain.shape,Xtest.shape,Ytest.shape)

(1760, 4) (1760, 1) (440, 4) (440, 1)


In [23]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [24]:
rf.fit(Xtrain,Ytrain)

<ipython-input-24-36f7ce9c386a>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(Xtrain,Ytrain)


RandomForestClassifier()

In [25]:
ypred=rf.predict(Xtest)

In [26]:
print(classification_report(Ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      0.88      0.93        16
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00        21
           3       1.00      1.00      1.00        14
           4       1.00      1.00      1.00        18
           5       1.00      0.89      0.94        19
           6       1.00      1.00      1.00        24
           7       0.88      0.94      0.91        16
           8       1.00      1.00      1.00        23
           9       0.88      0.82      0.85        17
          10       1.00      1.00      1.00        17
          11       1.00      1.00      1.00        26
          12       1.00      0.94      0.97        18
          13       1.00      1.00      1.00        15
          14       1.00      1.00      1.00        23
          15       0.93      1.00      0.96        13
          16       0.93      0.93      0.93        29
          17       1.00    

In [29]:
x=[[26.00373964,62.144510200000006,6.559817161000002,153.477776]]
op=rf.predict(x)
l[int(op)]

'coffee'

In [30]:
CropPrediction = "croplabel.pkl"  

with open(CropPrediction, 'wb') as file:  
    pickle.dump(rf, file)

In [31]:
with open(CropPrediction, 'rb') as file:  
    croplabel = pickle.load(file)

croplabel

RandomForestClassifier()

In [32]:
a = croplabel.predict([[26.00373964,62.144510200000006,6.559817161000002,153.477776]])  
print(a)

[21]


In [ ]:
'''
npk wala
'''

In [22]:
#data1=pd.read_csv("C:/Users/yagne/Desktop/anaconda/croppred/Crop_recommendation.csv")

In [26]:
'''l=list(data1['label'].unique())
print(l)
print(type(l))'''

['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas', 'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate', 'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple', 'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee']
<class 'list'>


In [28]:
'''from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
data1['label'] = lb_make.fit_transform(data1['label'])'''

In [32]:
#data1['label'].unique()

array([20, 11,  3,  9, 18, 13, 14,  2, 10, 19,  1, 12,  7, 21, 15,  0, 16,
       17,  4,  6,  8,  5])

In [33]:
#data1

N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536     20
1      85  58  41    21.770462  80.319644  7.038096  226.655537     20
2      60  55  44    23.004459  82.320763  7.840207  263.964248     20
3      74  35  40    26.491096  80.158363  6.980401  242.864034     20
4      78  42  42    20.130175  81.604873  7.628473  262.717340     20
...   ...  ..  ..          ...        ...       ...         ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507      5
2196   99  15  27    27.417112  56.636362  6.086922  127.924610      5
2197  118  33  30    24.131797  67.225123  6.362608  173.322839      5
2198  117  32  34    26.272418  52.127394  6.758793  127.175293      5
2199  104  18  30    23.603016  60.396475  6.779833  140.937041      5

[2200 rows x 8 columns]

In [33]:
feat2=data1[["temperature","humidity","ph","rainfall","label"]]

In [34]:
tar2=data1[["N","P","K"]]

In [35]:
rf2=RandomForestClassifier()

In [36]:
from sklearn.model_selection import train_test_split
Xtrainmine, Xtestmine, Ytrainmine, Ytestmine = train_test_split(feat2,tar2,test_size = 0.2,random_state =2)

In [37]:
rf2.fit(Xtrainmine,Ytrainmine)

RandomForestClassifier()

In [38]:
ypredmine=rf2.predict(Xtestmine)

In [40]:
x=[[26.00373964,62.144510200000006,6.559817161000002,153.477776,21]]
op=rf2.predict(x)
op

array([[113,  33,  34]], dtype=int64)

In [41]:
CropPrediction = "cropNPK.pkl"  

with open(CropPrediction, 'wb') as file:  
    pickle.dump(rf2, file)

In [42]:
with open(CropPrediction, 'rb') as file:  
    croppickelNPK = pickle.load(file)

croppickelNPK

RandomForestClassifier()

In [44]:
a = croppickelNPK.predict([[25.0756354,80.52389148,7.778915154,257.0038865,0]])  
print(a)

[[66 53 41]]
